In [1]:
import streamlit as st 
import pandas as pd 
dict = { 
        "name": ["harry", "rohan" , "skill", "shubh"],
        "marks":[30,90,56,89],
        "city":["rampur", "kolkatta", "bareily", "kota"]
        }

In [ ]:
df = pd.DataFrame(dict)
df

    name  marks      city
0  harry     30    rampur
1  rohan     90  kolkatta
2  skill     56   bareily
3  shubh     89      kota

In [8]:
df.to_csv("freinds_noIndex.csv", index=False)

In [ ]:
df.head(2)

    name  marks      city
0  harry     30    rampur
1  rohan     90  kolkatta

In [10]:
df.tail(2)

    name  marks     city
2  skill     56  bareily
3  shubh     89     kota

In [12]:
df.describe()

           marks
count   4.000000
mean   66.250000
std    28.871843
min    30.000000
25%    49.500000
50%    72.500000
75%    89.250000
max    90.000000

In [15]:
yash =  pd.read_csv("people.csv")

In [18]:
yash.head(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [21]:
yash["First Name"][2] = " yashber"

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_30704\1641258485.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  yash["First Name"][2] = " yashber"
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_30704\1641258485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yash["First Name"][2] = " yashber"

In [25]:
aa=yash.head(5)

In [26]:
yash.to_csv("people.csv")

In [27]:
aa

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,yashber,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [29]:
aa.index = [1,2,3,4,5]

In [31]:
aa

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
1,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
2,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
3,3,DbeAb8CcdfeFC2c,yashber,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
4,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
5,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon