In [26]:
import pandas as pd 
import numpy  as np

In [27]:
ser = pd.Series(np.random.rand(34))

In [28]:
type(ser)

pandas.core.series.Series

In [29]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [33]:
type(newdf)
newdf.head()

          0         1         2         3         4
0  0.088440  0.449711  0.536479  0.077092  0.070391
1  0.917208  0.909637  0.001250  0.368484  0.872572
2  0.625588  0.176383  0.946286  0.158732  0.989227
3  0.155568  0.701406  0.375520  0.827295  0.507458
4  0.680337  0.000177  0.348209  0.856276  0.687829

In [34]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.502052    0.506174    0.509685    0.516087    0.493948
std      0.282889    0.286510    0.289131    0.282653    0.289849
min      0.004763    0.000177    0.001250    0.013663    0.000793
25%      0.260160    0.259744    0.250005    0.276586    0.249653
50%      0.517524    0.508276    0.522040    0.521191    0.507176
75%      0.726001    0.747831    0.758329    0.772963    0.736014
max      0.993241    0.999410    0.997925    0.988909    0.999552

In [35]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [36]:
newdf[0][0]= " yash"

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7792\978149388.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]= " yash"
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7792\978149388.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' yash' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]= " yash"

In [37]:
newdf

            0         1         2         3         4
0        yash  0.449711  0.536479  0.077092  0.070391
1    0.917208  0.909637  0.001250  0.368484  0.872572
2    0.625588  0.176383  0.946286  0.158732  0.989227
3    0.155568  0.701406  0.375520  0.827295  0.507458
4    0.680337  0.000177  0.348209  0.856276  0.687829
..        ...       ...       ...       ...       ...
329  0.218076  0.645950  0.438746  0.397928  0.342513
330  0.273045  0.686438  0.424362  0.894782  0.311382
331  0.925955  0.012512  0.172752  0.670656  0.946917
332   0.61064  0.286503  0.941049  0.369816  0.412556
333  0.623152  0.217399  0.665933  0.955655  0.272269

[334 rows x 5 columns]

In [40]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [42]:
newdf.head()

          0         1         2         3         4
0      yash  0.449711  0.536479  0.077092  0.070391
1  0.917208  0.909637  0.001250  0.368484  0.872572
2  0.625588  0.176383  0.946286  0.158732  0.989227
3  0.155568  0.701406  0.375520  0.827295  0.507458
4  0.680337  0.000177  0.348209  0.856276  0.687829

In [45]:
newdf.head().index

Index([0, 1, 2, 3, 4], dtype='int32')

In [46]:
newdf.head().columns

RangeIndex(start=0, stop=5, step=1)

In [48]:
newdf.head().to_numpy()

array([[' yash', 0.44971082398765616, 0.5364789133917558,
        0.07709193518074953, 0.07039131627268591],
       [0.917208433198469, 0.9096367786412473, 0.001249767402629054,
        0.3684840650886999, 0.8725721990808369],
       [0.6255882868659303, 0.17638320729802448, 0.9462864162409717,
        0.1587323419944029, 0.9892272827428084],
       [0.15556803586790657, 0.7014063366909336, 0.37551976684175814,
        0.8272950853670158, 0.5074575721664843],
       [0.6803370884661437, 0.00017658053503799565, 0.34820856112532106,
        0.8562761542424708, 0.6878288197036919]], dtype=object)

In [51]:
newdf[0][0]= 0.3

In [52]:
newdf.head()

          0         1         2         3         4
0       0.3  0.449711  0.536479  0.077092  0.070391
1  0.917208  0.909637  0.001250  0.368484  0.872572
2  0.625588  0.176383  0.946286  0.158732  0.989227
3  0.155568  0.701406  0.375520  0.827295  0.507458
4  0.680337  0.000177  0.348209  0.856276  0.687829

In [54]:
newdf.head().dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [56]:
newdf.head(10).T

,0,1,2,3,4,5,6,7,8,9
0,0.3,0.917208,0.625588,0.155568,0.680337,0.242354,0.547167,0.089115,0.621544,0.146608
1,0.449711,0.909637,0.176383,0.701406,0.000177,0.074088,0.097535,0.856962,0.880081,0.843889
2,0.536479,0.00125,0.946286,0.37552,0.348209,0.369023,0.569045,0.6118,0.581293,0.4606
3,0.077092,0.368484,0.158732,0.827295,0.856276,0.829006,0.564758,0.633432,0.10014,0.092359
4,0.070391,0.872572,0.989227,0.507458,0.687829,0.538322,0.388112,0.821838,0.709575,0.940125

In [58]:
newdf.head().sort_index(axis=0 , ascending=False)

          0         1         2         3         4
4  0.680337  0.000177  0.348209  0.856276  0.687829
3  0.155568  0.701406  0.375520  0.827295  0.507458
2  0.625588  0.176383  0.946286  0.158732  0.989227
1  0.917208  0.909637  0.001250  0.368484  0.872572
0       0.3  0.449711  0.536479  0.077092  0.070391

In [61]:
a=newdf[0]
a

0           0.3
1      0.917208
2      0.625588
3      0.155568
4      0.680337
         ...
329    0.218076
330    0.273045
331    0.925955
332     0.61064
333    0.623152
Name: 0, Length: 334, dtype: object

In [63]:
type(a)

pandas.core.series.Series

In [76]:
newdf2 = newdf.head()
newdf2[0][0]= 55
newdf

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7792\3146785682.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]= 55
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7792\3146785682.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]= 55

            0         1         2         3         4
0          55  0.449711  0.536479  0.077092  0.070391
1    0.917208  0.909637  0.001250  0.368484  0.872572
2    0.625588  0.176383  0.946286  0.158732  0.989227
3    0.155568  0.701406  0.375520  0.827295  0.507458
4    0.680337  0.000177  0.348209  0.856276  0.687829
..        ...       ...       ...       ...       ...
329  0.218076  0.645950  0.438746  0.397928  0.342513
330  0.273045  0.686438  0.424362  0.894782  0.311382
331  0.925955  0.012512  0.172752  0.670656  0.946917
332   0.61064  0.286503  0.941049  0.369816  0.412556
333  0.623152  0.217399  0.665933  0.955655  0.272269

[334 rows x 5 columns]

In [75]:
newdf2 = newdf.head().copy()
newdf2[0][0]= 44
newdf

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7792\3344628892.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]= 44
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7792\3344628892.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]= 44

            0         1         2         3         4
0          55  0.449711  0.536479  0.077092  0.070391
1    0.917208  0.909637  0.001250  0.368484  0.872572
2    0.625588  0.176383  0.946286  0.158732  0.989227
3    0.155568  0.701406  0.375520  0.827295  0.507458
4    0.680337  0.000177  0.348209  0.856276  0.687829
..        ...       ...       ...       ...       ...
329  0.218076  0.645950  0.438746  0.397928  0.342513
330  0.273045  0.686438  0.424362  0.894782  0.311382
331  0.925955  0.012512  0.172752  0.670656  0.946917
332   0.61064  0.286503  0.941049  0.369816  0.412556
333  0.623152  0.217399  0.665933  0.955655  0.272269

[334 rows x 5 columns]