In [2]:
import pandas as pd 
import numpy as np

newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

hnewdf = newdf.head()
hnewdf

          0         1         2         3         4
0  0.453382  0.118269  0.066532  0.192082  0.432651
1  0.981951  0.292173  0.297312  0.291880  0.124345
2  0.536019  0.196397  0.947917  0.317449  0.975581
3  0.023911  0.711315  0.785101  0.721040  0.670056
4  0.084184  0.391843  0.606660  0.464241  0.548755

In [3]:
hnewdf.loc[0,0]= 12

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3668\1738294643.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hnewdf.loc[0,0]= 12

In [4]:
hnewdf.columns = list("ABCDE")

In [5]:
hnewdf

           A         B         C         D         E
0  12.000000  0.118269  0.066532  0.192082  0.432651
1   0.981951  0.292173  0.297312  0.291880  0.124345
2   0.536019  0.196397  0.947917  0.317449  0.975581
3   0.023911  0.711315  0.785101  0.721040  0.670056
4   0.084184  0.391843  0.606660  0.464241  0.548755

In [6]:
hnewdf.loc[0,"A"]= 99
hnewdf

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3668\1501132722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hnewdf.loc[0,"A"]= 99

           A         B         C         D         E
0  99.000000  0.118269  0.066532  0.192082  0.432651
1   0.981951  0.292173  0.297312  0.291880  0.124345
2   0.536019  0.196397  0.947917  0.317449  0.975581
3   0.023911  0.711315  0.785101  0.721040  0.670056
4   0.084184  0.391843  0.606660  0.464241  0.548755

In [7]:
hnewdf= hnewdf.drop(0, axis= 1 )

KeyError: '[0] not found in axis'

In [ ]:
hnewdf

           A         B         C         D         E
0  99.000000  0.879484  0.718926  0.605241  0.300258
1   0.318667  0.808659  0.611457  0.310549  0.039312
2   0.187054  0.573269  0.908988  0.842328  0.555793
3   0.361950  0.309983  0.176046  0.625508  0.329532
4   0.809307  0.819982  0.375505  0.561158  0.394561

In [ ]:
hnewdf.loc[[1,2], ["C", "D"]]

          C         D
1  0.611457  0.310549
2  0.908988  0.842328

In [ ]:
hnewdf.loc[[1,2], :]

          A         B         C         D         E
1  0.318667  0.808659  0.611457  0.310549  0.039312
2  0.187054  0.573269  0.908988  0.842328  0.555793

In [ ]:
hnewdf.loc[:, ["C", "D"]]

          C         D
0  0.718926  0.605241
1  0.611457  0.310549
2  0.908988  0.842328
3  0.176046  0.625508
4  0.375505  0.561158

In [ ]:
newdf.columns = list("ABCDE")
newdf.loc[(newdf["A"]< 0.3)]

            A         B         C         D         E
2    0.187054  0.573269  0.908988  0.842328  0.555793
5    0.068058  0.663127  0.974677  0.063247  0.461996
11   0.148856  0.836011  0.142138  0.038628  0.533365
12   0.048349  0.031485  0.850934  0.584143  0.999749
18   0.210969  0.995214  0.070128  0.694613  0.058661
..        ...       ...       ...       ...       ...
307  0.292225  0.020510  0.668360  0.647886  0.716919
310  0.245615  0.517842  0.914087  0.936939  0.565084
313  0.086762  0.898947  0.673274  0.001269  0.353665
322  0.293563  0.713314  0.309756  0.235026  0.939851
332  0.216301  0.169532  0.382506  0.915075  0.122780

[101 rows x 5 columns]

In [ ]:
newdf.columns = list("ABCDE")
newdf.loc[(newdf["A"and"C"]<0.3) & (newdf["B"] >0.1)]

            A         B         C         D         E
3    0.361950  0.309983  0.176046  0.625508  0.329532
6    0.908467  0.713590  0.187012  0.618292  0.687404
10   0.594125  0.427439  0.034504  0.965373  0.325866
11   0.148856  0.836011  0.142138  0.038628  0.533365
18   0.210969  0.995214  0.070128  0.694613  0.058661
..        ...       ...       ...       ...       ...
301  0.281301  0.202130  0.269297  0.464196  0.216843
305  0.396770  0.770656  0.169342  0.150550  0.748805
312  0.638614  0.427254  0.121381  0.701613  0.779595
320  0.629158  0.249951  0.177105  0.494751  0.245386
323  0.894095  0.324084  0.288085  0.802812  0.577216

[88 rows x 5 columns]

In [ ]:
hnewdf.columns = list("ABCDE")
hnewdf.loc[(hnewdf["A"and"C"]<0.3) & (hnewdf["B"] >0.1)]

         A         B         C         D         E
3  0.36195  0.309983  0.176046  0.625508  0.329532

In [9]:
hnewdf

           A         B         C         D         E
0  99.000000  0.118269  0.066532  0.192082  0.432651
1   0.981951  0.292173  0.297312  0.291880  0.124345
2   0.536019  0.196397  0.947917  0.317449  0.975581
3   0.023911  0.711315  0.785101  0.721040  0.670056
4   0.084184  0.391843  0.606660  0.464241  0.548755

In [8]:
hnewdf.iloc[0][4]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3668\229241448.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  hnewdf.iloc[0][4]

0.43265082669759225

In [ ]:
newdf.iloc[[0, 5], [1,2]]

          B         C
0  0.879484  0.718926
5  0.663127  0.974677

In [ ]:
hnewdf.drop([0])

          A         B         C         D         E
1  0.318667  0.808659  0.611457  0.310549  0.039312
2  0.187054  0.573269  0.908988  0.842328  0.555793
3  0.361950  0.309983  0.176046  0.625508  0.329532
4  0.809307  0.819982  0.375505  0.561158  0.394561

In [ ]:
hnewdf.drop(["D"] , axis=1, inplace=True)

In [ ]:
hnewdf

           A         B         C         E
0  99.000000  0.879484  0.718926  0.300258
1   0.318667  0.808659  0.611457  0.039312
2   0.187054  0.573269  0.908988  0.555793
3   0.361950  0.309983  0.176046  0.329532
4   0.809307  0.819982  0.375505  0.394561

In [ ]:
hnewdf.drop([1,3] , axis=0, inplace=True)

KeyError: '[1, 3] not found in axis'

In [ ]:
hnewdf

           A         B         C         E
0  99.000000  0.879484  0.718926  0.300258
2   0.187054  0.573269  0.908988  0.555793
4   0.809307  0.819982  0.375505  0.394561

In [ ]:
hnewdf.reset_index(drop = True , inplace=True)
hnewdf

   index          A         B         C         E
0      0  99.000000  0.879484  0.718926  0.300258
1      2   0.187054  0.573269  0.908988  0.555793
2      4   0.809307  0.819982  0.375505  0.394561

   index          A         B         C         E
0      0  99.000000  0.879484  0.718926  0.300258
1      2   0.187054  0.573269  0.908988  0.555793
2      4   0.809307  0.819982  0.375505  0.394561

In [ ]:
# Yeh line us extra 'index' naam ke column ko jad se delete kar degi
hnewdf.drop(columns=['index'], inplace=True, errors='ignore')

# Ab display karke dekho
hnewdf

           A         B         C         E
0  99.000000  0.879484  0.718926  0.300258
1   0.187054  0.573269  0.908988  0.555793
2   0.809307  0.819982  0.375505  0.394561

In [ ]:
hnewdf.reset_index(drop = True , inplace=True)

In [ ]:
hnewdf

           A         B         C         E
0  99.000000  0.879484  0.718926  0.300258
1   0.187054  0.573269  0.908988  0.555793
2   0.809307  0.819982  0.375505  0.394561

In [ ]:
hnewdf.loc[[0,2],"C"] = None
hnewdf

           A     B     C         E
0  99.000000  None  None  0.300258
1   0.187054  None  None  0.555793
2   0.809307  None  None  0.394561

In [ ]:
hnewdf["C"].isnull()

0    False
1    False
2    False
3    False
4    False
Name: C, dtype: bool

In [ ]:
hnewdf["C"].notnull()

0    True
1    True
2    True
3    True
4    True
Name: C, dtype: bool

In [ ]:
hnewdf.loc[[0,2],["E"]] = None
hnewdf

           A     B     C         E     e
0  99.000000  None  None       NaN  None
1   0.187054  None  None  0.555793   NaN
2   0.809307  None  None       NaN  None

In [ ]:
hnewdf.drop("e" , axis = 1, inplace=True )

In [ ]:
hnewdf["E"].isnull()

0     True
1    False
2     True
Name: E, dtype: bool

In [ ]:
hnewdf.dtypes

A    float64
B     object
C     object
E    float64
dtype: object

In [ ]:
hnewdf.iloc[[0, 0]] = 0.3434

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8284\521631665.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hnewdf.iloc[[0, 0]] = 0.3434