In [20]:
import pandas as pd
data = pd.read_excel("GENAIroadmap.xlsx")
data

,Section,Topic,Completed,revision,Confidence (1-5),Study Date,Hours Spent,Notes
0,Python Basics,Introduction - What We will Learn In This Course,yes,NaN,NaN,NaN,NaN,NaN
1,Python Basics,Course Materials,yes,NaN,NaN,NaN,NaN,NaN
2,Python Basics,Getting Started With VS Code,yes,NaN,NaN,NaN,NaN,NaN
3,Python Basics,Different Ways Of Creating Python Environment,yes,NaN,NaN,NaN,NaN,NaN
4,Python Basics,Solve-Conda Not Recognized Issue,yes,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
220,Generative AI,Introduction To MCP,No,NaN,NaN,NaN,NaN,NaN
221,Generative AI,Important Components Of MCP,No,NaN,NaN,NaN,NaN,NaN
222,Generative AI,Communication Between Components,No,NaN,NaN,NaN,NaN,NaN
223,Generative AI,Demo Of MCP With Claude Desktop,No,NaN,NaN,NaN,NaN,NaN
224,Generative AI,Build Me a Personalized AI Tutor Using LangCha...,No,NaN,NaN,NaN,,NaN

In [32]:
data.iloc[0,0]

'36-37'

In [76]:
import pandas as pd
data1 = pd.read_excel("GENAIroadmap.xlsx" , sheet_name = "resource") 
data1 =data1.head()
data1

,35,Operator Overloading,Python OOPs Playlist (Dunder Methods),Corey Schafer (YouTube)
0,36-37,Streamlit Basics & ML App,Streamlit Tutorials & Crash Course,Data Professor (YouTube)
1,38-61,NLP Core (Tokenization to Word2Vec),Natural Language Processing Playlist / CampusX...,Krish Naik / CampusX (YouTube)
2,62-93,"Deep Learning, RNN, LSTM, GRU",Deep Learning Playlist (PyTorch/TF),Aladdin Persson / Krish Naik
3,94-110,Transformers & Attention Mechanism,Let's build GPT from scratch / Neural Networks,Andrej Karpathy / 3Blue1Brown
4,111-140,"GenAI, LangChain Ecosystem, Embeddings",Complete Generative AI Playlist 2026,Krish Naik (YouTube)

In [ ]:
data1.iloc[1]
data1.iloc[0]

35                                                                    36-37
Operator Overloading                              Streamlit Basics & ML App
Python OOPs Playlist (Dunder Methods)    Streamlit Tutorials & Crash Course
Corey Schafer (YouTube)                            Data Professor (YouTube)
Name: 0, dtype: object

In [89]:
data1["Operator Overloading"]

0                 Streamlit Basics & ML App
1       NLP Core (Tokenization to Word2Vec)
2             Deep Learning, RNN, LSTM, GRU
3        Transformers & Attention Mechanism
4    GenAI, LangChain Ecosystem, Embeddings
Name: Operator Overloading, dtype: object

In [95]:
data1[[35, "Operator Overloading"]]

        35                    Operator Overloading
0    36-37               Streamlit Basics & ML App
1    38-61     NLP Core (Tokenization to Word2Vec)
2    62-93           Deep Learning, RNN, LSTM, GRU
3   94-110      Transformers & Attention Mechanism
4  111-140  GenAI, LangChain Ecosystem, Embeddings

In [96]:
data1[0:2]

,35,Operator Overloading,Python OOPs Playlist (Dunder Methods),Corey Schafer (YouTube)
0,36-37,Streamlit Basics & ML App,Streamlit Tutorials & Crash Course,Data Professor (YouTube)
1,38-61,NLP Core (Tokenization to Word2Vec),Natural Language Processing Playlist / CampusX...,Krish Naik / CampusX (YouTube)

In [99]:
data1

,35,Operator Overloading,Python OOPs Playlist (Dunder Methods),Corey Schafer (YouTube)
0,36-37,Streamlit Basics & ML App,Streamlit Tutorials & Crash Course,Data Professor (YouTube)
1,38-61,NLP Core (Tokenization to Word2Vec),Natural Language Processing Playlist / CampusX...,Krish Naik / CampusX (YouTube)
2,62-93,"Deep Learning, RNN, LSTM, GRU",Deep Learning Playlist (PyTorch/TF),Aladdin Persson / Krish Naik
3,94-110,Transformers & Attention Mechanism,Let's build GPT from scratch / Neural Networks,Andrej Karpathy / 3Blue1Brown
4,111-140,"GenAI, LangChain Ecosystem, Embeddings",Complete Generative AI Playlist 2026,Krish Naik (YouTube)

In [98]:
data1.iloc[1]

35                                                                                   38-61
Operator Overloading                                   NLP Core (Tokenization to Word2Vec)
Python OOPs Playlist (Dunder Methods)    Natural Language Processing Playlist / CampusX...
Corey Schafer (YouTube)                                     Krish Naik / CampusX (YouTube)
Name: 1, dtype: object

In [104]:
data1["Operator Overloading"][1]

'NLP Core (Tokenization to Word2Vec)'

In [120]:
data1[1]["Operator Overloading"]

KeyError: 1

In [111]:
data1[1:2][["Operator Overloading" , "Python OOPs Playlist (Dunder Methods)"]]

,Operator Overloading,Python OOPs Playlist (Dunder Methods)
1,NLP Core (Tokenization to Word2Vec),Natural Language Processing Playlist / CampusX...

In [112]:
data1.iloc[0]

35                                                                    36-37
Operator Overloading                              Streamlit Basics & ML App
Python OOPs Playlist (Dunder Methods)    Streamlit Tutorials & Crash Course
Corey Schafer (YouTube)                            Data Professor (YouTube)
Name: 0, dtype: object

In [113]:
data1.iloc[:,0]

0      36-37
1      38-61
2      62-93
3     94-110
4    111-140
Name: 35, dtype: object

In [118]:
data1.iloc[0,3]

'Data Professor (YouTube)'